com:
  adarsh:
    espark:
      application:
        appConfig:
          appName: "Espark sqllight Application"
        dbConfig:
          dbPath: "db/store/espark.db"
          dbScript: "db/scripts/espark.sql"
      